language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV=python2.6
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.3
      env: TOXENV=python3.3
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5

os:
  - linux

install:
  - pip install tox

script: 
  - tox
