language: python

cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          env:
              - TOXENV=python2.7

        - os: linux
          python: 3.5
          sudo: required
          env:
              - TOXENV=python3.5

        - os: linux
          python: 3.6
          sudo: required
          env:
              - TOXENV=python3.6

        - os: linux
          dist: xenial
          python: 3.7
          sudo: required
          env: TOXENV=python3.7

        - os: linux
          dist: xenial
          python: 3.6
          sudo: required
          env:
              - TOXENV=build
              - DEPLOY_FILE='dist/sqlitebiter_*.deb'

        - os: osx
          language: generic
          env:
              - TOXENV=python3.6

        - os: osx
          language: generic
          env:
              - TOXENV=build
              - DEPLOY_FILE='dist/sqlitebiter_macos_*'

install:
    - travis_retry bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh

notifications:
    slack:
        secure: EHpNEhPxWbvByJouszVg5JIU9BBURFQnHlMEJDudWnK8i0hF37OYKkC8oSbvi2Hz+/bCW4eFStwuTu17RA9diUI6F4ZQ+H0OygI5NqlGSlty0sQpfpxOTSVlqGupKJtZRG5yeqzCVEdXYLZOQH8q54yUADxpjaPkdvCoOrcPB/xBe8vxpUc4uPtYQVeCJCOij0y+3nEwOOu/A8JBk0Uhx9690qKHzYwv3V93M4OjYeWntEcmcbJaLj+BCVV+DT3rPoUeweoZHwd/0euyKR/NmjR/y0uIsIkcjKpwDACaPIzzoQUD7VMf+91yebqI42t5ukg4fDArGE8jkQrRPsTKBdBP7n32n8PShWVypXR/CN/qYZvWwoVkuyYp2KudJIXm9SzWuW0sYjL4BaI9/sQs8iZfXOW2UJfErwNn5gybkxc/59hgtR955ceYWjKSm++KzG9AYb3c7MqY2HHWGdGxNHD6dv2tnTQJ1FUNC5wuOwmOsg0EjHD+o67zYuvOOsjA2EfgjFVqsWLBy7Uh9fQVBOUpb3NCFA0ZDK02xaBtuZSzhT2vCviUkRsvgIy51yzPt6ldeadKtogCUKrQU3U9M0R3ZkoJSZaN74ZHA33IFtCKfnIkZaoJ1w+DRGPLw8D31CI/dxIoeVUjsCYhDuPLxcF/L1x5GS/8tJHXcZEGK/c=

before_deploy:
    - bash -x build_package.sh

deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: HuldCWcSiKXmem3i/n361fwUkomBQg9/yOna3HxA+Yulyx+qRcsYWnfYRV3JXtaF598E2dD7mtLgoLdcObxgXrQ7rdXYc/RqqUTvr+o16ZvZjjbOhoxPmCk3sDjvjFgFfI4Bpi2xJ8aBj73mu4Udp7CfdXfFumgQggChtytDgxZm2zr0cepIipvqGkWSa6Ka0Otwx+6PYw8ca7L0CxqKrtNp0tnwBsQxdbnBt+deAVHK+EZ6GOfQlVEBoaMeJl5bKMZaarnl+NeNVdcI9bFCtV9j/L5UDrBvOv6TzBUv5hTPh53BYN4k6D6dvsM8AtlMOv8yVgh8zYSbJTOdBDftD0jiDIl//QLqUDOM6HFxUfcchAqOlW7nMGvxxDfUqFuqVS1U3WMUBgZJ5XFNKj56X6ksR2w9it9TviBGX+0eObZ0y43k5FAKymxnS4RzFyDRoZp8b5S2evRnO7MuTVO+KM/dL3oyOwcdAwodc0+iRyUKfX71mNYfTuR/Tj9qjRUyUwna9yqZ1uJxU3nkwcrd7j8XXSsCiVnNnI8UWnuToCQZu5s4ACUM/pAH+tkrGfO51gLTfBvHgz80fF7cscgd2WxqrtTEAp4otWj7fZALR4umHpAyiJMtouceQhJAow0BFgs4lmGGvj9f/4AwaxUPpAMbnmqtzzGeMLwsR6MvL44=
    file_glob: true
    file: $DEPLOY_FILE
    on:
        tags: true
        condition: "$TOXENV = build"
