build: false
environment:
  matrix:
    - PYTHON: "C:/Python38-x64"

configuration:
  - Release

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

notifications:
  - provider: Slack
    auth_token:
      secure: JyTQAtBzpPYiWK3eRTz/U+rvmAKopqIWE19ti4vSL/IRygV3jUVUkwET1VyTlrqOeYfNx3Kfcp7eUmHCHxFCgw==
    channel: notifications

for:
  - matrix:
      only:
        - configuration: Release
          PYTHON: "C:/Python38-x64"

    before_deploy:
      - "%PYTHON%/Scripts/pip.exe install .[all,buildexe]"
      - "build_win_package.bat"
      - ps: appveyor PushArtifact dist/sqlitebiter_win_x64.zip

    deploy:
      - provider: GitHub
        tag: $(APPVEYOR_REPO_TAG_NAME)
        description: "Release description"
        auth_token:
          secure: l3Edds+qJSbk42FBi9+s1Fu7wlTkGHGeDI52i1zvDjZXbNk1VTDASioYJiFb9f3M
        draft: false
        prerelease: true
        on:
          appveyor_repo_tag: true # deploy on tag push only
